# Generated by Django 2.2.3 on 2019-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_serviceteam2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godwin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
