# Generated by Django 2.2.3 on 2019-08-08 10:06

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('class1', models.CharField(max_length=55)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=255)),
                ('tel', phone_field.models.PhoneField(max_length=31)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
