# Generated by Django 2.2.3 on 2019-08-08 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('class1', models.CharField(max_length=55)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'student1',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
