# Generated by Django 2.2.3 on 2019-08-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190809_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Praying',
            new_name='Praya',
        ),
    ]
