# Generated by Django 2.2.3 on 2019-08-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190809_1904'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pra',
            table='praya',
        ),
    ]
