# Generated by Django 2.2.3 on 2019-08-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190809_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pra',
            table='pra',
        ),
    ]
