# Generated by Django 2.2.3 on 2019-08-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190809_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steward',
        ),
    ]
