# Generated by Django 2.2.3 on 2019-08-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_evan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evan',
            table=None,
        ),
    ]
