# Generated by Django 2.2.3 on 2019-08-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190809_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evan',
            new_name='Evangelism',
        ),
    ]
