# Generated by Django 2.2.3 on 2019-08-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190809_2019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evangelism',
            table='evangelism',
        ),
    ]
