# Generated by Django 2.2.3 on 2019-08-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190809_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evangelism',
        ),
    ]
