# Generated by Django 2.2.3 on 2019-08-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventstwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('anouncer', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('event_main_img', models.ImageField(blank=True, upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_steward',
                'ordering': ['-created_on'],
            },
        ),
    ]
