# Generated by Django 2.2.3 on 2019-08-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_event_teaching_min_teaching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_teaching',
            name='slug',
        ),
    ]
