# Generated by Django 2.2.3 on 2019-08-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_event_teaching_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='min_teaching',
            old_name='photo_img',
            new_name='passport_main_Img',
        ),
    ]
