# Generated by Django 2.2.3 on 2019-08-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_min_teaching_passport_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='min_teaching',
            name='passport',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
