# Generated by Django 2.2.3 on 2019-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190814_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_account',
            name='description',
            field=models.TextField(),
        ),
    ]
