# Generated by Django 2.2.3 on 2019-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20190814_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrp_account',
            name='credit_currency',
        ),
        migrations.RemoveField(
            model_name='pgrp_account',
            name='debit_currency',
        ),
        migrations.AlterField(
            model_name='pgrp_account',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='pgrp_account',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
