# Generated by Django 2.2.3 on 2019-08-15 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20190815_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrp_account',
            name='id',
        ),
        migrations.AddField(
            model_name='pgrp_account',
            name='sn',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pgrp_account',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pgrp_account',
            name='description',
            field=models.CharField(default='Default', max_length=300),
        ),
    ]
