# Generated by Django 2.2.3 on 2019-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20190815_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgrp_account',
            name='sn',
            field=models.IntegerField(default=0, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
