# Generated by Django 2.2.3 on 2019-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20190815_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrp_account',
            name='sn',
        ),
        migrations.AddField(
            model_name='pgrp_account',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
