# Generated by Django 2.2.3 on 2019-08-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190815_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pgrp_Account',
        ),
    ]
