# Generated by Django 2.2.3 on 2019-08-15 14:45

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_delete_pgrp_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pgrp_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.CharField(default='Default', max_length=300)),
            ],
        ),
    ]
