# Generated by Django 2.2.3 on 2019-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20190815_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgrp_account',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
