# Generated by Django 2.2.3 on 2019-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20190815_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrp_account',
            name='sn',
        ),
        migrations.AlterField(
            model_name='pgrp_account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
