# Generated by Django 2.2.3 on 2019-08-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20190815_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventsgeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('anouncer', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('event_main_img', models.ImageField(blank=True, upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_general',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('news_img', models.ImageField(blank=True, upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-created_on'],
            },
        ),
    ]
