# Generated by Django 2.2.3 on 2019-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20190818_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_intercessory',
            name='eventp_img',
        ),
        migrations.AddField(
            model_name='event_intercessory',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
