# Generated by Django 2.2.3 on 2019-08-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20190818_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='min_evangelical',
            options={'ordering': ['-first_name']},
        ),
        migrations.AlterModelOptions(
            name='min_intercessory',
            options={'ordering': ['-first_name']},
        ),
        migrations.AlterModelOptions(
            name='min_praiseworship',
            options={'ordering': ['-first_name']},
        ),
        migrations.AlterModelOptions(
            name='min_stewards',
            options={'ordering': ['-first_name']},
        ),
        migrations.AlterModelOptions(
            name='min_teaching',
            options={'ordering': ['-first_name']},
        ),
        migrations.AlterModelOptions(
            name='min_visitation',
            options={'ordering': ['-first_name']},
        ),
    ]
