# Generated by Django 2.2.3 on 2019-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('modeOfPayment', models.CharField(max_length=250)),
                ('income', models.IntegerField(max_length=100)),
                ('debit', models.IntegerField(max_length=100)),
                ('tellerNo', models.IntegerField(max_length=20)),
                ('dateOfPayment', models.CharField(max_length=20)),
                ('addressOfPayee', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
