# Generated by Django 2.2.3 on 2019-07-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cusname', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('amount_paid', models.IntegerField(max_length=100)),
                ('total', models.IntegerField(max_length=100)),
                ('balance', models.IntegerField(max_length=100)),
                ('phone', models.IntegerField(max_length=15)),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
    ]
